
export const projects = [
    {
        title: "Scrum Board",
        description: "A visual tool that helps teams track tasks and monitor progress during project management. Built from scratch using Vue 3 and BootStrap.",
        technologies: ["Vue.Js", "JavaScript", "Bootstrap", "Vite"],
        image: "/assets/scrumboard.webp",
        github: "https://github.com/talhaiftikhar12549/Scrum-Board",
        live: "https://scrum-board-123.netlify.app/",
    },
    {
        title: "Project Management Tool",
        description: "Cloned the Redmine Agile Board to track changes during development. Implemented drag & drop functionality to visualize changes.",
        technologies: ["React", "JavaScript", "Bootstrap", "Vite"],
        image: "/assets/scrum-board (1).webp",
        github: "https://github.com/talhaiftikhar12549/Project-Management-Software",
        live: "https://project-management-software123.netlify.app/",
    },
    {
        title: "Weather Walley",
        description: "Weather Forecasting app that tracks weekly weather around the globe. Integrated the OpenWeather API with a Leaflet map to track location.",
        technologies: ["Vue.Js", "JavaScript", "Tailwind", "Node"],
        image: "/assets/weather walley logo.webp",
        github: "https://github.com/talhaiftikhar12549/Weather-Walley",
        live: "https://weather-walley.netlify.app/",
    },
    {
        title: "Food X",
        description: "Online food ordering website that serves Oriental, Continental, and Chinese cuisine. Get your favorite food delivered to your doorstep. ",
        technologies: ["React", "JavaScript", "Tailwind", "Vite"],
        image: "/assets/Foodx Logo.webp",
        github: "https://github.com/talhaiftikhar12549/FoodX",
        live: "https://food-x-123.netlify.app/",
    },
    {
        title: "Talha Portfolio",
        description: "My personal portfolio website, built from scratch using React, showcases my skill set in an aesthetic and visually appealing way.",
        technologies: ["React", "Particle.Js", "Tailwind", "Vite"],
        image: "/assets/Talha Portfolio Logo.webp",
        github: "https://github.com/talhaiftikhar12549/talhaiftikhar",
        live: "https://talhaiftikhar.netlify.app/",
    },
    {
        title: "Fabric Kitchensink",
        description: "Designed and created objects freely on a canvas. Integrated the Fabric.js library with React.js to build an interactive canvas application. ",
        technologies: ["Fabric.Js", "JavaScript", "React", "Tailwind", "Vite"],
        image: "/assets/FabricjsCanvas.webp",
        github: "https://github.com/talhaiftikhar12549/Fabric-Kitchen-Sink-Version-5",
        live: "https://fabricjs-kitchen-sink.netlify.app/",
    },
    {
        title: "Netflix Clone",
        description: "Cloned a Netflix app landing page to replicate its design and functionality. Built the page from scratch using Tailwind CSS. ",
        technologies: ["HTML/CSS", "JavaScript", "Tailwind"],
        image: "/assets/Netflix Logo.webp",
        github: "https://github.com/talhaiftikhar12549/Netflix-Clone",
        live: "https://streaming-app-clone.netlify.app/",
    },
    {
        title: "Little Lemon",
        description: "Make your evening memorable with Little Lemon Restaurant. Order your food or book your table for an aesthetic dine-in experience.",
        technologies: ["React", "JavaScript", "Tailwind", "Vite"],
        image: "/assets/Little Lemon.webp",
        github: "https://github.com/talhaiftikhar12549/Little-Lemon",
        live: "https://little-lemon-resturant-project.netlify.app/",
    },
];
